
language: node_js
node_js:
  - "8.2.1"

install:
  - npm install newman

before_script:
  - node --version
  - npm --version
  - node_modules/.bin/newman --version
  - sudo chown -R travis ./travis/pull_data.sh
  - sudo chmod +x ./travis/pull_data.sh
  - ./travis/pull_data.sh

script:
  - node_modules/.bin/newman --version

